// <auto-generated />
namespace FakeEstateWeb.Migrations.Listings
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IntroducePhotos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IntroducePhotos));
        
        string IMigrationMetadata.Id
        {
            get { return "201407092223484_IntroducePhotos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
